FROM node:22-alpine
WORKDIR /app
RUN corepack enable
COPY package.json pnpm-workspace.yaml ./
COPY apps/feigua-worker ./apps/feigua-worker
COPY packages ./packages
RUN pnpm install --filter @data-tw/feigua-worker... --prod=false
CMD ["pnpm","--filter","@data-tw/feigua-worker","start"]