FROM node:22-alpine
WORKDIR /app
RUN corepack enable
COPY package.json pnpm-workspace.yaml ./
COPY apps ./apps
COPY packages ./packages
RUN pnpm install --filter @data-tw/dashboard... --prod=false
RUN pnpm --filter @data-tw/dashboard build
EXPOSE 3003
CMD ["pnpm","--filter","@data-tw/dashboard","start"]