FROM node:22-alpine
WORKDIR /app
RUN corepack enable
COPY package.json pnpm-workspace.yaml ./
COPY apps/admin ./apps/admin
COPY packages ./packages
RUN pnpm install --filter @data-tw/admin... --prod=false
RUN pnpm --filter @data-tw/admin build
EXPOSE 3004
CMD ["pnpm","--filter","@data-tw/admin","start"]